Dev
NAZARfedun/GOlang_Test pull request #1
Opened 2020-06-26 21:07 UTC by NAZARfedun

Logger and Config logic.

2020-06-26 21:18 UTC, diabeticMike requested changes
shit

2020-06-26 21:29 UTC, diabeticMike commented on main.go
> +// }
Don't left redundant comments

2020-06-26 21:33 UTC, diabeticMike commented on config/config.go
> +}
rename this file to envconfig.go

2020-06-26 21:33 UTC, diabeticMike requested changes
Overall ok, but i think you need to add config.json file with your configuration

2020-07-15 13:40 UTC, NAZARfedun commented on main.go
> +// }
DONE!

2020-07-15 13:40 UTC, NAZARfedun commented on config/config.go
> +}
DONE!

2020-07-15 13:45 UTC, diabeticMike commented on config/config.go
> +}
revert dir name to config pls

2020-07-15 13:46 UTC, diabeticMike requested changes
.

2020-07-15 13:53 UTC, diabeticMike approved these changes

2020-07-15 13:53 UTC, merged